all:	configure

configure:	socnetv.spec.in Makefile.in configure.ac
		@autoheader
		@autoconf
		@rm -rf *.cache

clean:
	@if [ -f Makefile ]; then make clean; fi || true
	@rm -rvf Makefile configure config.*
	@rm -rvf *.cache *.log *.status *.pro *.spec *.desktop
