name: Validate-YAMLs

on:
  push:
    branches: [ main, develop ]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML file
        run:
          yamllint  -d "{extends: relaxed, rules: {line-length: {max: 120}}}"  ${{ github.workspace }}/.github/workflows/*.yml

