extends: default

rules:
  document-start: disable
  truthy: disable
  line-length:
    max: 280
    level: warning
  trailing-spaces: disable
  new-line-at-end-of-file: enable
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
