extends: default

rules:
  document-start: disable
  truthy: disable
  line-length:
    max: 200
    level: warning
  trailing-spaces: enable
  new-line-at-end-of-file: enable
  empty-lines:
    max: 0